### PR TITLE
feat: update for libvips v8.15.1

### PR DESCRIPTION
**Pull request by negezor**
Hi! It's me again. This PR is updating the environment a bit and generating bindings for libvips 1.15.1.

### CODE REVIEW

**Comment by GamerBene19** [comment]
@negezor Do you have time to resolve the merge conflicts and update this PR?
After that, perhaps @bassco can find some time to review and merge it.
No pressure though to both of you :smile:

**Comment by GamerBene19** [comment]
Thank you both very much :smile:

**Comment by bassco** [comment]
@negezor - I messed up the github actions, allowing the release to run in the forked repos of contributors 🤕 

This [semantic-release-bot](https://github.com/olxgroup-oss/libvips-rust-bindings/pull/72/commits/44d65db4403987eae44acbfabb2169f0f4dc0130) commit gave it away 😞.

**Comment by bassco** [comment]
@negezor - apologies for closing the PR. Replaced with #101 so that you don't need to play git games and remove commits from this PR.

Hopefully the work in https://github.com/olxgroup-oss/libvips-rust-bindings/commit/a36fca72c7f363406048704a80331aaf2a665a19 will stop this from occurring in future and will make contributions easier.

**Pull request closed without merging**
